### PR TITLE
Implement battery block

### PR DESCRIPTION
**Pull request by remi-dupre**

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
LGTM. Just before I merge it, do you think it's better to move `async` development to a fork of `i3status-rust` right away or later?

**Comment by remi-dupre** [comment]
Well I've actually been thinking a little about it, I have a suggestion on how we could proceed to include all this work in `i3status-rust`.

I am pretty sure it wouldn't be too hard to extend the `Block` trait to add an implementation of `run` for all "legacy" blocks, by doing so we could proceed in several steps:

 - first replace the scheduler with async mechanism, together with this idea of compatibility layer for old block implementations
 - then open a PR block by block to replace old implementation with idiomatic async

This could be a decent solution since submitting a huge re-implementation at once would make it a hell to review and it would be very hard to track changes that have been made in blocks in the main repo (which would make compatibility even harder to keep). Maybe it would also be more appealing for people to join the efforts, if anyone is interesting in it ^^

**Comment by MaxVerevkin** [comment]
> I am pretty sure it wouldn't be too hard to extend the Block trait to add an implementation of run for all "legacy" blocks

In general yes, it shouldn't be too difficult for simple blocks. However, I don't know how to combine the two different click handling mechanisms. Also, how to deal with those blocks that rely on channels to request the update? Spawn two tasks for every "legacy" block (one for clicks, one for channel update request)?

I can imagine that maintaining this "API compatibility layer" would be a nightmare. Hope I'm wrong.

**Comment by MaxVerevkin** [comment]
@remi-dupre Well, I tried implementing that "compatibility layer" and it *is* a nightmare. I don't think it worth the time spend. If fact, there is no good reason to implement it, since every block should be modified to work with it anyway.

**Comment by remi-dupre** [comment]
@MaxVerevkin 
> @remi-dupre Well, I tried implementing that "compatibility layer" and it _is_ a nightmare. I don't think it worth the time spend. If fact, there is no good reason to implement it, since every block should be modified to work with it anyway.

I managed to implement something here: https://github.com/MaxVerevkin/swaystatus/compare/master...remi-dupre:legacy-block (with `disk_space` block implementation copied from i3status-rs).

I agree that in the end all blocks should be re-implemented through swaystatus, but I think it would be an extremely tedious process to do everything in a single PR, starting with reviews, which may be extremely slow and require to keep updated with changes made to i3status-rs during the process. Plus we could even start merging some content before all blocks are re-implemented :D

**Comment by MaxVerevkin** [comment]
@remi-dupre

> but I think it would be an extremely tedious process to do everything in a single PR

Yeah, I agree with that.

> I managed to implement something here: master...remi-dupre:legacy-block (with disk_space block implementation copied from i3status-rs).

Looks better than what I had :smile:

The last thing to do is to implement `tx_update_request` support for blocks such as `sound`, right?

**Pull request merged**
